name: Go Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  coverage:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.23.4"

      - name: Run Tests and Generate Coverage Report
        run: go test -race -timeout 60s -coverpkg=./... -coverprofile=coverage.raw.txt -covermode atomic ./... && cat coverage.raw.txt | grep -Ev "internal/" > coverage.txt

      - name: Generate Coverage Badge
        uses: vladopajic/go-test-coverage@v2
        with:
          profile: coverage.txt
          local-prefix: github.com/leonhwangprojects/bice
          threshold-total: 90
          badge-file-name: coverage.svg
